version: '3.8'

services:
  soso-api:
    build:
      context: .
      dockerfile: services/soso-api/build/Dockerfile
    container_name: soso-api
    env_file: services/soso-api/config/.env
    ports:
      - "8080:8080"
    depends_on:
      soso-database:
        condition: service_healthy

  soso-database:
    image: mysql:8.0
    container_name: soso-database
    env_file: services/soso-api/config/.env
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./services/soso-api/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u root -p$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 5s
      retries: 5

  soso-api-document:
    image: swaggerapi/swagger-ui:latest
    container_name: soso-api-document
    ports:
      - "9419:8080"
    environment:
      SWAGGER_JSON: /docs.yaml
    volumes:
      - ./services/soso-api/api/docs.yaml:/docs.yaml:ro
    depends_on:
      - soso-api

  soso-api-document-deploy:
    image: swaggerapi/swagger-ui:latest
    container_name: soso-api-document-deploy
    ports:
      - "9418:8080"
    environment:
      SWAGGER_JSON: /swagger.yaml
    volumes:
      - ./services/soso-api/api/swagger.yaml:/swagger.yaml:ro
    depends_on:
      - soso-api

  soso-web:
    build:
      context: services/soso-web
      dockerfile: Dockerfile.nextjs  # Next.js用Dockerfileを指定
      args:
        NEXT_PUBLIC_API_BASE_URL: http://localhost:8080
    container_name: soso-web
    volumes:
      - ./services/soso-web:/app # ホストとコンテナ間でソースコードを同期
      - /app/node_modules # node_modulesは同期対象から除外
    ports:
      - "3000:3000"
    depends_on:
      - soso-api

  soso-web-storybook:
    build:
      context: services/soso-web
      dockerfile: Dockerfile.storybook  # Storybook用Dockerfileを指定
    container_name: soso-web-storybook
    ports:
      - "6006:6006" # ホスト側の6006ポートとコンテナをマッピング
    volumes:
      - ./services/soso-web:/app # ホストとコンテナ間でソースコードを同期
      - /app/node_modules # node_modulesは同期対象から除外
    depends_on:
      - soso-api

volumes:
  db_data:
