version: '3.8'

services:
  swagger-ui:
    image: swaggerapi/swagger-ui:latest
    container_name: soso-swagger-ui
    restart: unless-stopped
    ports:
      - "9419:8080"
    environment:
      SWAGGER_JSON: /app/api/docs/swagger.yaml
    volumes:
      - ./app:/app:ro
