version: "3.8"

services:
  soso-api-document:
    image: swaggerapi/swagger-ui:latest
    container_name: soso-api-document
    ports:
      - "9419:8080"
    environment:
      SWAGGER_JSON: /app/swagger.yaml
    volumes:
      - ./app/api/docs/swagger.yaml:/app/swagger.yaml:ro

  soso-database:
    image: mysql:8.0
    container_name: soso-database
    env_file: .env
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  soso-api:
    build:
      context: ./app/api
      dockerfile: Dockerfile
    container_name: soso-api
    volumes:
      - ./app/api:/app
    env_file: .env            # ← API側もDB接続情報だけ読み込む
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
    ports:
      - "8080:8080"
    depends_on:
      - soso-database

volumes:
  db_data:
