# Next.js 用のビルドステージ
# FROM node:20-alpine AS builder # 本番の時はこの行をコメント外して3行目をコメントアウト
FROM node:20-alpine
WORKDIR /app

COPY .env .env

COPY package*.json ./
RUN npm install

COPY . .

CMD ["npm", "run", "dev"]

# 本番の時は15行目以下をコメント外して12行目をコメントアウト
# RUN npm run build 

# # 本番用の軽量イメージ
# FROM node:20-alpine
# WORKDIR /app

# ENV NODE_ENV=production

# COPY --from=builder /app ./

# EXPOSE 3000
# CMD ["npm", "start"]
